name: Build and Release

on:
    push:
        tags:
            - "*"

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: read
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Setup Python environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - run: python3 -m pip install -r requirements.txt
            - name: Verify setuptools-scm detected version
              run: python3 -m setuptools_scm
            - run: python3 -m build
            - name: Publish package to PyPi
              uses: pypa/gh-action-pypi-publish@release/v1
